Add cyrillic support
chrishoermann/zod-prisma-types pull request #303
Opened 2024-12-15 17:26 UTC by ProGamer2711

2025-02-05 20:20 UTC, chrishoermann requested changes
@ProGamer2711 Thanks for the PR - looks good to me. But before merging can you please change the `repository` in the package.json back to 

```
  "repository": {
    "type": "git",
    "url": "https://github.com/chrishoermann/zod-prisma-types.git"
  },
```

Thanks 😉

2025-02-05 20:23 UTC, ProGamer2711 commented
@chrishoermann sure I, don't even remember changing it... Will commit in about 10 minutes.

2025-02-05 20:30 UTC, ProGamer2711 commented
@chrishoermann Should be good now.

2025-02-08 20:28 UTC, chrishoermann approved these changes
thanks - will be available in the next release

2025-02-08 20:28 UTC, merged